name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
         github_user_name: "Jamshidi-Coding"
          outputs: dist/snake.svg

      - name: Push Snake
        uses: ad-m/github-push-action@master
        with:
          branch: master
          file: dist/snake.svg
